# Generated by Django 5.0.4 on 2024-08-15 03:12

import usuarios.querysets
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_created'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.querysets.UsuarioManager()),
            ],
        ),
    ]
