# Generated by Django 5.0.4 on 2024-08-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('condition', models.TextField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
