# Generated by Django 5.0.4 on 2024-08-14 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='usuarios.adress'),
        ),
    ]
