# Generated by Django 5.0.4 on 2024-08-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
    ]
