# Generated by Django 5.0.4 on 2024-08-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_nome_produto_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('PE', 'Pendente'), ('AC', 'A caminho'), ('ES', 'Esgotado'), ('PR', 'Em processamento'), ('DI', 'Descontinuado'), ('RE', 'Reservado'), ('DE', 'Devolvido')], default='AT', max_length=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='produtos.producttype'),
        ),
    ]
